name: 'Setup'
inputs:
  python-version:  # id of input
    description: 'Python version'
    required: true

runs:
  using: "composite"
  steps:
    - name: python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: install requirements
      shell: bash
      run: |
        pip install wheel
        pip install mypy
        pip install pytest
        pip install pylint
        pip install https://github.com/jeremiahrose/ocp-build-system/releases/download/7.7.1.0/cadquery_ocp-7.7.1-cp310-cp310-macosx_11_0_arm64.whl
        pip install .
