name: 'Setup'
inputs:
  python-version:  # id of input
    description: 'Python version'
    required: true

runs:
  using: "composite"
  steps:
    - name: python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: install requirements
      shell: bash
      run: |
        pip install wheel
        pip install mypy
        pip install pytest
        pip install pylint
        pip install https://github.com/jdegenstein/ocp-build-system/releases/download/7.8.1/cadquery_ocp-7.8.1-cp311-cp311-manylinux_2_35_x86_64.whl
        pip install .
