name: tests

on: [push, pull_request, workflow_dispatch]
jobs:

  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [
          "3.10",
          ]
        os: [flyci-macos-large-latest-m1]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: test
        run: |
          python -m pytest

